spring:
  application:
    name: project-devdojo
  threads:
    virtual:
      enabled: true
server:
    servlet:
      contextPath: /
    error:
      include-stacktrace: on_param
    tomcat:
      threads:
        max: 20
